// Generated by CoffeeScript 1.3.3
(function() {
  var createSelector, _es, _fuenf, _ist;

  createSelector = function(coordinates) {
    var c, s, _i, _len;
    s = "";
    for (_i = 0, _len = coordinates.length; _i < _len; _i++) {
      c = coordinates[_i];
      s += ".clock tr:nth-child(" + c[1] + ") td:nth-child(" + c[0] + "), ";
    }
    return s.substr(0, s.length - 2);
  };

  _es = createSelector([[1, 1], [2, 1]]);

  _ist = createSelector([[4, 1], [5, 1], [6, 1]]);

  _fuenf = createSelector([[8, 1], [9, 1], [10, 1], [11, 1]]);

  console.log(_es);

  this.clock = {
    start: function() {
      $(_es).addClass("active");
      $(_ist).addClass("active");
      return $(_fuenf).addClass("active");
    }
  };

}).call(this);
